### PR TITLE
Add sdk config argument to command, and create local.properties for Android project

### PR DESCRIPTION
**Pull request by thyrlian**
Really nice project, brilliant idea!  (I'm an alfi user ;)

Ruby can't read _$ANDROID_HOME_ directly from system environment variables, it's painful.  And usually for Android projects, developers wouldn't check their **local.properties** (with hardcoded Android SDK path inside) into git.  Thus when using dryrun, I've encountered problems `java.lang.RuntimeException: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.` even though I've set _$ANDROID_HOME_ to my system environment variables.

My solution is to have a local permanent config file to store Android SDK path info, which makes things easier.  So far we only need to store SDK path, so I didn't make the Config class too complicated (e.g. with key value pairs, save to a yaml, not necessary for now).

All tests are passed (and I've added some more).

Try this command and repo please:
`dryrun https://github.com/thyrlian/AwesomeValidation`
Before it didn't work, now it works perfectly.

And sorry, I don't have time to update the README file with latest command line usage, have to prepare for tomorrow's travel now, sorry ;)

Thank you so much for your time.

### CODE REVIEW

**Comment by cesarferreira** [comment]
Hey there mate :smile: thanks a lot for the contribution, it's because of this kind of things that I love the github community :) and thanks for the compliment!
I'm glad to hear that you're using **alfi**, it saves me a lot of time too :)

I've been using `AwesomeValidation` myself in a few projects for awhile now, great work and thanks for publishing it :smile: 

---

My review to your pull-request:

> Ruby can't read $ANDROID_HOME directly from system environment variables, it's painful. 

Actually you can:

``` ruby
sdk = `echo $ANDROID_HOME` # => "/Users/cesarferreira/Library/Android/sdk/"
```

> And usually for Android projects, developers wouldn't check their local.properties (with hardcoded Android SDK path inside) into git. Thus when using dryrun, I've encountered problems java.lang.RuntimeException: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

This is why in my recent push I force-delete the `local.properties` so `gradle` is forced to use the `$ANDROID_HOME` path for the SDK (no problem there anymore ;) )

> even though I've set $ANDROID_HOME to my system environment variables.

Now this is really weird, did you forced bash to refresh the variables? 
You can do it like this: `source ~/.bashrc`

Does your `.bashrc` has something like this?

> export ANDROID_HOME="/Users/cesarferreira/Library/Android/sdk/"

if you did all of this this, the output you get from this: `echo $ANDROID_HOME` should be your full path

> My solution is to have a local permanent config file to store Android SDK path info, which makes things easier. 

The permanent config file, assuming we delete the `local.properties` will always be the `$ANDROID_HOME` variable, so, in my opinion we don't need to persist that information in a third party file.

---

I've made a few tweaks on the tool having your problems and your code into consideration!

Can you update the gem to 0.4.0 to see if your problem is fixed?

> gem install dryrun

Your lib works great from my end
-dv9jhp_lgfwjm0ifgqd5g-2bcfr6dlnosigesp0tcm

You even created rspec tests :) awesome work mate :+1: 

Tet me know if this fixed your issue ;)

Safe travel!

**Comment by thyrlian** [comment]
Obrigado!

I actually tried `echo $ANDROID_HOME`, while it didn't work for me, I thought it was because of this kind of environment variable is not visible for its child process (ruby).  It works in plain terminal environment, but not with ruby.  And I believe that I have set the export command in my bashrc and zshrc.  It's really weird.  But I'm still travelling, will check everything you said when back home :)

Thanks again for your response and good job!

Buen fin de semana.

**Comment by thyrlian** [comment]
Sorry for my late reply.  Yes the newer gem works perfect.  Please close this pull request.  There was something wrong with my zsh environment variables.

Wish to see more interesting projects from you, keep on great job :+1: 

BTW, one of my project you might be interested [gradleman](https://github.com/thyrlian/gradleman), but so far it could barely prints the dependency "collisions" (not yet working, haven't got time to work on it).  Obrigado.

**Comment by cesarferreira** [comment]
Thanks a lot for your pull request man, greatly appreciated.
Folllow me on github then ;) I'll keep publishing new stuff.

Gradleman looks good, I'll keep a watch on that ;)

best regards

**Pull request closed without merging**
