### PR TITLE
New download folder destination

### PR DESCRIPTION
**Pull request by cesarferreira**
To prevent issues like #61 or #55

### CODE REVIEW

**Comment by cesarferreira** [comment]
@luispereira @tazesk or @krokyze can you try this branch to see if it fixes the problem?
I don't own any windows machine

**Comment by tazesk** [comment]
yes, you fix it !!! thank you.

**Comment by cesarferreira** [comment]
it's already on version `0.8.1`

**Comment by lizwangying** [comment]
hi, I use Windows. And I have this issue too. My dryrun verison is 0.8.1, but I still encounter this problem. Is something I did wrong？Thanks for your help anyway...

C:\Users\thinkpad>dryrun https://github.com/ksoichiro/Android-ObservableScrollView.git
Searching for devices...
Killing adb, there might be an issue with it...
No devices attached, but I'll run anyway


======================================================

 Something went wrong while executing this:
  $ git clone --depth 1 https://github.com/ksoichiro/Android-ObservableScrollView.git C:/Users/thinkpad/AppData/Local/Temp/dryrun/ksoichiro/Android-ObservableScrollView

======================================================

**Comment by cesarferreira** [comment]
works great on OSX, @luispereira can you try it on your windows machine?

**Comment by luispereira** [comment]
I also have the issue, although this is an issue regarding the project itself and not dryrun. 
I believe the gradle wrapper has some custom functionalities which does not support Windows System, such as "tr".

**Comment by cesarferreira** [comment]
Yeah, it's a BSD tool, it's not on windows

```
TR(1)                     BSD General Commands Manual                    TR(1)

NAME
     tr -- translate characters
```

**Pull request merged**
