### PR TITLE
Add custom build type, custom keystore path and adjust for custom generated applicationIDs

### PR DESCRIPTION
**Pull request by pavlospt**

### CODE REVIEW

**Comment by pavlospt** [comment]
@cesarferreira Did you have any time to review this one :) ?

**Comment by cesarferreira** [comment]
Hey man!

Sorry, it's next on my todo list :)

**Comment by pavlospt** [comment]
Nice :)

**Comment by cesarferreira** [comment]
Can you resolve the conflicts before I review please? :)

**Comment by pavlospt** [comment]
Ok, give me some time to check it and I will update you !

**Comment by pavlospt** [comment]
@cesarferreira Is it ok now?

**Comment by cesarferreira** [comment]
Something weird happened, look at the comparison: https://github.com/cesarferreira/dryrun/compare/master...Workable:master

**Comment by pavlospt** [comment]
I don't understand how this happened... I am checking it now. 

EDIT: It seems like I lost everything...going to have to search for a potential backup...

**Comment by cesarferreira** [comment]
Did you force push?

**Comment by pavlospt** [comment]
Yes, but after I have rebased from your upstream. I will have to check the reflog from my personal MacBook and force push the HEAD~1, in order to retrieve it. After rebasing you can only force push, but I don't get why it didn't find the rest of the files, that were already available on my master and your upstream master.

**Comment by cesarferreira** [comment]
I do rebasing too (at work) but it's so fricking dangerous :)

**Comment by pavlospt** [comment]
So far I never had such a problem, that is why I am so surprised. I do like loads of rebases as well !

**Comment by pavlospt** [comment]
Unfortunately reflog did not help. Even with resetting to the original commit, I still can not restore my code. Will keep trying a bit and then will close the PR and re-open a new one if I find the time to re-write everything.

**Comment by cesarferreira** [comment]
:/ how unlucky man

**Pull request closed without merging**
