### PR TITLE
Add possibility to run tests

### PR DESCRIPTION
**Pull request by ghostbuster91**
As discussed in #101

### CODE REVIEW

**Review by cesarferreira — APPROVED** [review]
everything looks good, just gonna test it now :)

**Comment by cesarferreira** [comment]
while running:
> ❯ dryrun https://github.com/cesarferreira/android-helloworld -t

got this:

```

**Review by cesarferreira — CHANGES_REQUESTED** [review]
while running:
> ❯ dryrun https://github.com/cesarferreira/android-helloworld -t

got this:

```
/Users/cesarferreira/code/github/dryrun/lib/dryrun/test_application_command.rb:25:in `run': undefined local variable or method `clear_app_data' for #<Dryrun::TestApplicationCommand:0x007fa324b5f620> (NameError)
	from /Users/cesarferreira/code/github/dryrun/lib/dryrun/android_project.rb:103:in `execute_command'
	from /Users/cesarferreira/code/github/dryrun/lib/dryrun.rb:208:in `call'
	from /Users/cesarferreira/code/github/dryrun/bin/dryrun:6:in `<top (required)>'
	from /Users/cesarferreira/.rvm/gems/ruby-2.4.1/bin/dryrun:22:in `load'
	from /Users/cesarferreira/.rvm/gems/ruby-2.4.1/bin/dryrun:22:in `<main>'
	from /Users/cesarferreira/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/cesarferreira/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ghostbuster91** [comment]
Hi, happy new year.
Can you take a second look at this PR?

**Comment by cesarferreira** [comment]
Yeah, will review it now :)

**Comment by cesarferreira** [comment]
My points:

- Can you squash the 17 commits into meaningful commits?
- have you noticed that there are 2 `-t` commands, one for the `--tag` and another one for `--test`? they are going to be conflicting with each other

the code looks amazing, I can tell you're a good ruby dev :) thanks

**Review by cesarferreira — CHANGES_REQUESTED** [review]
My points:

- Can you squash the 17 commits into meaningful commits?
- have you noticed that there are 2 `-t` commands, one for the `--tag` and another one for `--test`? they are going to be conflicting with each other

the code looks amazing, I can tell you're a good ruby dev :) thanks

**Comment by ghostbuster91** [comment]
Commits have been squashed. I replaced the letter 't' with an 'a', which stands now for 'android-tests' but any suggestions are welcome.

**Review by cesarferreira — CHANGES_REQUESTED** [review]
Please update the README and the `dryrun -h`

**Comment by ghostbuster91** [comment]
As I can see we don't need to update `dryrun -h`, because it is automatically generated.

**Review by cesarferreira — CHANGES_REQUESTED** [review]
While running `dryrun . -t` to run tests locally, it says "invalid option -a", does it happen to you too?

**Comment by ghostbuster91** [comment]
What do you mean by running `dryrun . -t` ? The `-t` abbreviation requires a tag. Nonetheless I cannot reproduce it. Can you provide more info? Also I am not sure if `.` is a valid github url.

**Comment by cesarferreira** [comment]
sorry, my bad, i meant `dryrun . -a` 

actually `dryrun .` should remove the need to use a URL and use the current directory

**Comment by ghostbuster91** [comment]
You are right. The behavior has changed. 
Here are the responsible lines:
```
      path = sample_project
      manifest_parsed = parse_manifest(path)

      if path == false && manifest_parsed == false
        puts "Couldn't open the sample project, sorry!".red
        exit 1
      end
```

During the development I changed this if statement to have disjunction instead of conjuction.
I believe I had a reason for that, but can't figure it out now. Anyway I restored the previous version, so now using dot works.

**Comment by cesarferreira** [comment]
Awesome, so can I do the final review? @ghostbuster91

**Comment by ghostbuster91** [comment]
I think so :)

**Comment by cesarferreira** [comment]
Released as `1.1.0`
thanks @ghostbuster91 !

**Pull request merged**
